import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import TopHeader from "@/components/TopHeader";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const josefin = Josefin_Sans({
  weight: ["300", "400", "600"], // Choose the font weights you need
  subsets: ["latin"], // Choose the subset you need (e.g., 'latin')
});

export const metadata: Metadata = {
  title: "Ecomemrce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefin.className}  antialiased`}>
        <TopHeader />
        <Header />
        <main className="w-full h-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
